### ISSUE TITLE
need to add unsexed back in #2

### ISSUE THREAD

**Issue by pete-hulson** [ben-williams/swo-sim#13]
https://github.com/ben-williams/swo-sim/blob/0bfc4388041be2045b86bbf27bdda7dd29342f4c/R/functions.R#L86

change this line to:

      bind_rows(.new_sexed, .new_unsexed) %>%

looks like the newly unsexed data never got added back into the resampled data - what was happening is that on the original unsexed data was kept so the unsexed estimates were constant across the iterations

**Comment by BenWilliams-NOAA** [comment]
yeah we kept them separate since didn't know what GAP wanted to do with them. if we change to `.anti_join(.new_sexed) %>%
  mutate(sex = 3) -> .new_unsexed` and then `bind_rows` we lose the specific id info (admittedly makes some large files) seems that info is no longer desired? also easy enough to revert back or make a variant if GAP needs that for VAST-based length/age comps
